title: Blog Communauté Technique Ouest - SOFTEAM Digital
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
url: https://softeamouest.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author: Blog Communauté Technique Ouest # add your name
author-img: logo-communaute-technique.png # add your photo
about-author: Blog de la communauté de SOFTEAM Digital # add description
softeam: https://www.softeamdigital.fr # add your Twitter handle
email: mehdi.elkouhen@softeam.fr # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-feed

collections:
  events:
    output: true
    permalink: /events/:path/
    title: Events

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "yarn.lock"]
